### ISSUE TITLE
Plan(s) for x86 support?

### ISSUE THREAD

**Issue by TheVietboi** [niutech/splitbrowser#11]
I'm aware that majority of OSs and and software support is fully migrating to x64, and having a different architecture support also mean double the work since they needed to be coded differently (which is why many emulation software/virtual machine also dropped their support for 32-bit system). Just a thought that it'd be nice to have this for smaller systems much like embedded or IoT environment.

If you don't have interest in it, that's fine. 

Cheers.

**Comment by niutech** [comment]
Sorry, but [WebKit](https://lists.webkit.org/pipermail/webkit-dev/2019-June/030699.html)/Ultralight/WebView2 are available only in 64-bit.
