### ISSUE TITLE
About the webkit build

### ISSUE THREAD

**Issue by ericoporto** [niutech/splitbrowser#4]
Hey, your project is the only one I found to get a reasonably updated webkit in Windows.

If you ever get back to it, please add the developer console from webkit. It would be super helpful to debug webkit issues on Windows.

**Comment by niutech** [comment]
You can right-click on a web page and select Inspect Element to open Web Inspector:

![Split Browser WebKit Inspector](https://user-images.githubusercontent.com/384997/222996440-931dc7ba-1896-459f-aa47-be54c493195c.png)

I will update the WebKit build to rev. 1803 soon.

**Comment by ioc2e3** [comment]
That

Here ( https://github.com/niutech/splitbrowser ) ...

Please continue update and provide Windows version ...

.
